// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace EuromoneyBca.Domain.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class TradeHistoryView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TradeHistoryView));
        
        string IMigrationMetadata.Id
        {
            get { return "201312051519120_TradeHistoryView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
