// <auto-generated />
namespace EuromoneyBca.Domain.Allocations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Bren : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bren));
        
        string IMigrationMetadata.Id
        {
            get { return "201401141414426_Bren"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
